#### ライブラリのインポート

In [ ]:
import numpy as np
import pandas as pd

#### 基本操作

##### データ型と属性

In [ ]:
# Numpyのデータ型：ndarray型
a1 = np.array([1, 2, 3])
a1
type(a1)

numpy.ndarray

In [ ]:
# 二次元ベクトル・三次元ベクトル
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# データの確認
a1.shape

(3,)

In [ ]:
# 次元の確認
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
# データ型の確認
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [ ]:
# 要素数の確認
a1.size, a2.size, a3.size

(3, 6, 18)

In [ ]:
# オブジェクトの型を確認
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# nparrayからデータフレームを作成
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##### 配列の作成

In [ ]:
# 0で埋め尽くされた配列
ones = np.zeros((2, 3))
ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 範囲を定めた配列
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
# ランダム配列①
ramdom_array = np.random.randint(0, 10, size=(3, 5))
ramdom_array

array([[8, 2, 3, 2, 6],
       [3, 6, 4, 3, 3],
       [2, 6, 6, 4, 8]])

In [ ]:
# ランダム配列②
ramdom_array2 = np.random.random((5, 3))
ramdom_array2

array([[0.89160707, 0.04553006, 0.68538931],
       [0.12846543, 0.87255064, 0.8058425 ],
       [0.61344642, 0.24688607, 0.34330495],
       [0.08045995, 0.22112392, 0.99540489],
       [0.82952819, 0.32599229, 0.35789085]])

In [ ]:
# ランダム配列③
ramdom_array3 = np.random.rand(5, 3)
ramdom_array3

array([[0.95140202, 0.44353019, 0.33400255],
       [0.85937248, 0.77766995, 0.83041395],
       [0.22648882, 0.90895653, 0.37460021],
       [0.8655211 , 0.74949761, 0.57655622],
       [0.28782062, 0.06686005, 0.32237007]])

In [ ]:
# ランダム配列④（再現性を確保）
np.random.seed(seed=42)
ramdom_array4 = np.random.randint(10, size=(5, 3))
ramdom_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

##### 列・行列の抽出

In [ ]:
# ユニークな要素の抽出
# return_index：True ＝ 元の配列の中での最初の出現位置のインデックスも返す
# return_counts：True ＝ 各ユニークな要素が元の配列に何回現れるかのカウントも返す
np.unique(ramdom_array4)

array([2, 3, 4, 5, 6, 7, 9])

In [ ]:
a1[0]

1

In [ ]:
a2[0]

array([1. , 2. , 3.3])

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 配列の作成
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]])

In [ ]:
# サイズと次元の確認
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [ ]:
# 4次元配列の最初の4個を抽出
a4[:, :, :, :4]

array([[[[4, 1, 7, 5],
         [4, 0, 9, 5],
         [0, 9, 2, 6],
         [8, 2, 4, 2]],

        [[4, 8, 6, 1],
         [8, 1, 9, 8],
         [4, 1, 3, 6],
         [2, 0, 3, 1]],

        [[3, 1, 5, 5],
         [3, 5, 1, 9],
         [9, 3, 7, 6],
         [7, 4, 1, 4]]],


       [[[9, 8, 8, 0],
         [6, 8, 7, 0],
         [7, 2, 0, 7],
         [2, 0, 4, 9]],

        [[9, 8, 6, 8],
         [1, 0, 6, 6],
         [4, 2, 7, 5],
         [0, 2, 4, 2]],

        [[4, 9, 6, 6],
         [9, 9, 2, 6],
         [3, 3, 4, 6],
         [3, 6, 2, 5]]]])

##### 配列の計算

In [ ]:
# 配列の計算（a1=([1, 2, 3])）
ones = np.ones(3)
a1 + ones

array([2., 3., 4.])

In [ ]:
# 四則演算
np.add(a1, ones), np.subtract(a1, ones), np.multiply(a1, ones), np.divide(a1, ones)

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]))

In [ ]:
# 指数計算
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# 対数計算
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# 総和
np.sum(a1)

6

In [ ]:
# 計算速度の比較（pythonのデータ型：pythonメソッド、numpy配列のデータ型：numpyメソッドを使う）
massive_array = np.random.random(100000)
%timeit sum(massive_array) # pythonのメソッド
%timeit np.sum(massive_array) # numpyのメソッド

34.3 ms ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
58.2 µs ± 2.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# 平均・最大値・最小値・標準偏差・分散
np.mean(a2), np.max(a2), np.min(a2), np.std(a2), np.var(a2)

(3.6333333333333333, 6.5, 1.0, 1.8226964152656422, 3.3222222222222224)

##### 形状の変更

In [ ]:
# 形状の確認
a2.shape

(2, 3)

In [ ]:
# 形状の変更
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape.shape

(2, 3, 1)

In [ ]:
# 行列の変更
a2.T.shape

(3, 2)

##### 内積

In [ ]:
# 行列の作成
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [ ]:
# 積
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
# 内積
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [ ]:
# 内積のサンプルプロダクト（各曜日の売上の総合計①）
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
# 各曜日のアイテムの売上個数（各曜日の売上の総合計②）
weekly_sales = pd.DataFrame(sales_amount, index=["月", "火", "水", "木", "金"], columns=["アイテム1", "アイテム2", "アイテム3"])
weekly_sales

アイテム1  アイテム2  アイテム3
月     12     15      0
火      3      3      7
水      9     19     18
木      4      6     12
金      1      6      7

In [ ]:
# アイテムの価格（各曜日の売上の総合計③）
item_prices = np.array([10, 8, 12])
item_prices = pd.DataFrame(item_prices.reshape(1, 3), index=["価格"], columns=["アイテム1", "アイテム2", "アイテム3"])
item_prices

アイテム1  アイテム2  アイテム3
価格     10      8     12

In [ ]:
# 各曜日の売上の総合計（各曜日の売上の総合計④）
daily_sales = np.dot(weekly_sales, item_prices.T)
daily_sales

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [ ]:
# データフレームに追加（各曜日の売上の総合計⑤）
weekly_sales["合計"] = daily_sales
weekly_sales

アイテム1  アイテム2  アイテム3   合計
月     12     15      0  240
火      3      3      7  138
水      9     19     18  458
木      4      6     12  232
金      1      6      7  142

##### 配列の比較

In [ ]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [ ]:
# 比較①
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
# 比較②
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
# 比較③
a1 > 5, a1 < 5

(array([False, False, False]), array([ True,  True,  True]))

##### 配列の並び替え

In [ ]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
# 並び替え（昇順）
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [ ]:
# 並び替えの結果をインデックス番号で確認
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [ ]:
# 配列の最大値をインデックス番号で返す
# axis=0：列ごとに処理、axis=1：行ごとに処理
np.argmax(random_array, axis=0), np.argmax(random_array, axis=1)

(array([1, 1, 1, 0, 0]), array([4, 1, 1]))